# Generated by Django 5.0 on 2023-12-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heros', '0002_remove_hero_age_remove_hero_alias_hero_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
