# Generated by Django 5.0 on 2023-12-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heros', '0004_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='description',
            field=models.TextField(),
        ),
    ]
