# Generated by Django 5.0 on 2023-12-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
